config/routes.rb
Rails.application.routes.draw do
  root to: 'pipelines#index'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}

  resources :statuses
  resources :pipelines do
    resources :leads
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :pipeline
end

app/models/pipeline.rb
class Pipeline < ApplicationRecord
  has_many :leads, dependent: :destroy
  has_many :statuses, dependent: :destroy
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :pipeline
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.create_from_provider(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email =  provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:update]
  before_action :authenticate_user!

  def new
    @lead = Lead.new
  end

  def create
    lead = AmoWrapper.add_lead(lead_params)
    if lead
      pipeline = Pipeline.find_by(id: lead_params['pipeline_id'])
      status   = Status.where(pipeline: pipeline.id, name: 'Зарегистрировано').first

      @lead           = Lead.new
      @lead.pipeline  = pipeline
      @lead.status_id = status.id
      @lead.email     = lead_params['email']
      @lead.uid       = lead['_embedded']['items'][0]['id']

      respond_to do |format|
        if @lead.save
          format.html { redirect_to pipeline, notice: 'Lead was successfully created.' }
        else
          format.html { render :new }
        end
      end

    end
  end

  def update
    AmoWrapper.update_lead(params)
    @pipeline = @lead.pipeline
    @lead.price = params['price']
    @lead.status_id = @lead.pipeline.statuses.where(pipeline_id: @pipeline.id, name: 'Оплачено').last.id

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @pipeline, notice: 'Lead was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lead
    @lead = Lead.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lead_params
    params.require(:lead).permit(:uid, :email, :price, :pipeline_id)
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  def google_oauth2
    @user = User.create_from_provider(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user
    else
      flash[:error] = 'There was a problem signing you in through Google. Please register or try again later'
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try again later'
    redirect_to new_user_registration_url
  end
end

app/controllers/pipelines_controller.rb
class PipelinesController < ApplicationController
  before_action :set_pipeline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @pipelines = Pipeline.all
  end

  def show
    @leads = AmoWrapper.leads
    if @leads
      @leads = @leads.select { |lead| lead["pipeline_id"].to_s == @pipeline.uid }
      @leads.each do |lead|

        Lead.find_or_create_by(
          uid: lead['id'],
          email: lead['name'],
          pipeline_id: lead['pipeline_id'],
          status_id: lead['status_id']
        )
      end
      @leads = @pipeline.leads
    end
  end

  def new
    @pipeline = Pipeline.new
  end

  def create
    pipeline = AmoWrapper.add(pipeline_params).first[1]
    if pipeline
      @pipeline       = Pipeline.new
      @pipeline.uid   = pipeline['id']
      @pipeline.title = pipeline['name']

      pipeline['statuses'].each do |st|
        status          = Status.new
        status.uid      = st[1]['id']
        status.pipeline = @pipeline
        status.name     = st[1]['name']
        status.save!
      end


      respond_to do |format|
        if @pipeline.save
          format.html { redirect_to @pipeline, notice: 'Pipeline was successfully created.' }
          format.json { render :show, status: :created, location: @pipeline }
        else
          format.html { render :new }
          format.json { render json: @pipeline.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  def update
    respond_to do |format|
      if @pipeline.update(pipeline_params)
        format.html { redirect_to @pipeline, notice: 'Pipeline was successfully updated.' }
        format.json { render :show, status: :ok, location: @pipeline }
      else
        format.html { render :edit }
        format.json { render json: @pipeline.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pipeline.destroy
    respond_to do |format|
      format.html { redirect_to pipelines_url, notice: 'Pipeline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pipeline
    @pipeline = Pipeline.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pipeline_params
    params.require(:pipeline).permit(:uid, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li><%= link_to "Воронки", pipelines_path, class: 'btn btn-primary' %></li>
      <li><%= link_to "Создать воронку", new_pipeline_path, class: 'btn btn-primary' %></li>
    </ul>

    <span class="navbar-text">
      <% if user_signed_in? %>
        <b><%= current_user.email %></b> |
        <%= link_to "Выйти", destroy_user_session_path, :method => :delete %>
      <% end %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if user_signed_in? %>
    <%= render 'layouts/navbar' %>
  <% end %>

  <br><br>
  <div class="container text-center">
    <%= yield %>
  </div>
  </body>
</html>

app/views/leads/_form.html.erb
<%= form_with(model: lead, url: pipeline_leads_path, local: true) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
        <% lead.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :email, class: 'form-control', placeholder: 'Email' %>
  </div>

  <%= form.submit 'Создать', class: 'btn btn-primary' %>
  <%= link_to 'Назад', pipelines_path, class: 'btn btn-outline-secondary' %>

  <%= form.hidden_field :pipeline_id, value: params['pipeline_id'] %>

<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form', lead: @lead %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leads</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th>Email</th>
      <th>Price</th>
      <th>Pipeline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.uid %></td>
        <td><%= lead.email %></td>
        <td><%= lead.price %></td>
        <td><%= lead.pipeline %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>Новая карточка</h1>

<%= render 'form', lead: @lead %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @lead.uid %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Price:</strong>
  <%= @lead.price %>
</p>

<p>
  <strong>Pipeline:</strong>
  <%= @lead.pipeline %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/pipelines/_form.html.erb
<%= form_with(model: pipeline, local: true) do |form| %>
  <% if pipeline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pipeline.errors.count, "error") %> prohibited this pipeline from being saved:</h2>

      <ul>
      <% pipeline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Название воронки' %>
  </div>

  <%= form.submit 'Создать', class: 'btn btn-primary' %>
  <%= link_to 'Назад', pipelines_path, class: 'btn btn-outline-secondary' %>
<% end %>

app/views/pipelines/edit.html.erb
<h1>Editing Pipeline</h1>

<%= render 'form', pipeline: @pipeline %>

<%= link_to 'Show', @pipeline %> |
<%= link_to 'Back', pipelines_path %>

app/views/pipelines/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="">Воронки</h1>

<div class="row">
  <% @pipelines.each do |pipeline| %>
    <div class="col-sm-3">

      <div class="card">
        <div class="card-body">
          <h4 class="card-title"><%= link_to pipeline.title, pipeline %>
            | <%= link_to 'X', pipeline, method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-primary' %></h4>
        </div>
      </div>
      <br>
    </div>
    <br>
<% end %>
</div>

app/views/pipelines/new.html.erb
<h1>Новая воронка</h1>

<%= render 'form', pipeline: @pipeline %>

app/views/pipelines/show.html.erb
<p id="notice"><%= notice %></p>
<div class="text-left">
  <h4><%= @pipeline.title %>
    | <%= link_to 'Создать карточку', new_pipeline_lead_path(pipeline_id: @pipeline.id), class: 'btn btn-primary' %></h4>

</div>
<hr>

<table class="table table-hover">
  <thead class="table-info">
  <tr>
    <th>Почта</th>
    <th>Стоимость</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% if @leads.present? %>

    <% @leads.each do |lead| %>


      <tr>
        <td><%= lead['email'] %></td>
        <% if lead['price'].present? %>

          <td><%= lead['price'] %></td>

        <% else %>

          <td> <%= form_with(url: pipeline_lead_path(@pipeline, lead), method: 'put') do %>
            <%= text_field_tag :price, nil, class: 'form-control', placeholder: 'Сумма оплаты' %>
            <%= hidden_field_tag :pipeline_id, @pipeline.uid %>
          </td>

          <td>
            <%= submit_tag "Подтвердить оплату", class: 'btn btn-primary' %>
          </td>
        <% end %>

        <% end %>

      </tr>

    <% end %>

  <% end %>
  </tbody>
</table>

app/views/pipes/_form.html.erb
<%= form_with(model: pipe, local: true) do |form| %>
  <% if pipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pipe.errors.count, "error") %> prohibited this pipe from being saved:</h2>

      <ul>
      <% pipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pipes/edit.html.erb
<h1>Editing Pipe</h1>

<%= render 'form', pipe: @pipe %>

<%= link_to 'Show', @pipe %> |
<%= link_to 'Back', pipes_path %>

app/views/pipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pipes <%= link_to '+', new_pipe_path, class: 'badge badge-primary' %></h1>

  <% @pipes.each do |pipe| %>


    <div class="card">
      <h5 class="card-header"><%= pipe.last %> | <%= pipe.first %>
        <%= link_to 'X', pipe_path(pipe.first), method: :delete, data: { confirm: 'Are you sure?' }, class: 'badge badge-primary' %>
      </h5>

      <div class="card-body">
        <h5 class="card-title">

          <%= form_with(url: "/add_lead", method: "get") do %>
            <%= label_tag(:email, "email:") %>
            <%= email_field_tag(:email) %>

            <%= hidden_field_tag :pipe_uid, pipe.first %>
            <%= submit_tag("Зарегистрировать") %>
          <% end %>
        </h5>

        <table class="table table-hover">
          <thead class="table-info">
          <tr>
            <th>email</th>
            <th>price</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
          <% if @leads.present? %>

            <% @leads.each do |lead| %>
              <% if lead['pipeline_id'] == pipe.first %>

                <tr>
                  <td><%= lead['name'] %></td>
                  <td> <%= form_with(url: "/update_lead", method: "get") do %>

                      <%= label_tag(:price, "Price:") %>
                      <%= text_field_tag(:price) %>

                      <%= hidden_field_tag :pipe_uid, pipe.first %>
                      <%= submit_tag("Оплачено") %>
                    <% end %>
                  </td>

                </tr>

              <% end %>
            <% end %>

          <% end %>
          </tbody>
        </table>


      </div>
    </div>

    <br>
  <% end %>

app/views/pipes/new.html.erb
<h1>New Pipe</h1>

<%= render 'form', pipe: @pipe %>

<%= link_to 'Back', pipes_path %>

app/views/pipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pipe.name %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @pipe.uid %>
</p>

<%= link_to 'Edit', edit_pipe_path(@pipe) %> |
<%= link_to 'Back', pipes_path %>